#!/usr/bin/python3
# Copyright 2024 Dimitri John Ledkov
# SPDX-License-Identifier: Apache-2.0

import argparse
import json
import sys
try:
    from packageurl.contrib import purl2url
except ImportError as e:
    print(e)
    print("Error: Please pip install packageurl-python")
    sys.exit(1)

def SpdxPurl2Url(fp=None):
    spdx = json.load(fp)
    for package in spdx.get('packages'):
        for externalRef in package.get('externalRefs'):
            if externalRef.get('referenceType') == 'purl':
                download_url=purl2url.get_download_url(externalRef['referenceLocator'])
                if download_url:
                    print(download_url)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog='spdx-purl2url',
        description='Extract repository and download URLs from SPDX'
        )
    parser.add_argument('filename',
                        nargs='+',
                        type=open,
                        help='SPDX JSON file(s) to parse')
    args = parser.parse_args()
    for spdx in args.filename:
        SpdxPurl2Url(spdx)
